/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ascensao.view;

import br.com.ascensao.controller.BatalhaController;
import br.com.ascensao.model.Equipes;
import br.com.ascensao.model.SemiDeus;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;

public class ArenaFrame extends javax.swing.JFrame {
    
    private Equipes arena;
    private BatalhaController controller;
    private JPanel painelLadoA;
    private JPanel painelLadoB;
    private JTextArea logBatalha;
    private JButton btnAcao;

    private ArrayList<PainelSemiDeus> cardsA = new ArrayList<>();
    private ArrayList<PainelSemiDeus> cardsB = new ArrayList<>();

    public ArenaFrame() {

        setTitle("Ascensão ao Olimpo - Torneio Oficial");
        setSize(1000, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout(10, 10));

        arena = new Equipes();
        arena.formarEquipes();

        controller = new BatalhaController(arena);

        montarLayout();
        povoarArena();

        setLocationRelativeTo(null);
        setVisible(true);

        //initComponents();

    }

    private void montarLayout(){

        JPanel centro = new JPanel (new GridLayout (1, 2, 20, 0));
        centro.setBackground(new Color(40,40,45));

        painelLadoA = new JPanel (new FlowLayout(FlowLayout.CENTER, 10, 10));
        painelLadoB = new JPanel (new FlowLayout(FlowLayout.CENTER, 10, 10));

        centro.add(new JScrollPane(painelLadoA));
        centro.add(new JScrollPane(painelLadoB));
        add(centro, BorderLayout.CENTER);

        JPanel inferior = new JPanel (new BorderLayout());
        logBatalha = new JTextArea(6, 30);
        logBatalha.setEditable(false);

        btnAcao = new JButton("PROXIMA RODADA");
        btnAcao.setFont(new Font("Arial", Font.BOLD, 18));
        btnAcao.addActionListener(e -> clicarNoBotao());

        inferior.add(new JScrollPane(logBatalha), BorderLayout.CENTER);
        inferior.add(btnAcao, BorderLayout.SOUTH);
        add(inferior, BorderLayout.SOUTH);
       
    }

    private void povoarArena(){
    
        for (SemiDeus s : arena.getLadoA()) {
            PainelSemiDeus p = new PainelSemiDeus(s);
            cardsA.add(p);
            painelLadoA.add(p);
        }
        for (SemiDeus s : arena.getLadoB()) {
            PainelSemiDeus p = new PainelSemiDeus(s);
            cardsB.add(p);
            painelLadoB.add(p);
        }
    }

    private void clicarNoBotao(){

        //teste 
        controller.turnoCombate(arena.getLadoA(), arena.getLadoB());
        controller.turnoCombate(arena.getLadoB(), arena.getLadoA());

        //teste
        for (PainelSemiDeus p : cardsA) p.atualizarPainel();
        for (PainelSemiDeus p : cardsB) p.atualizarPainel();

        logBatalha.append("O combate ruge! Rodada finalizada.\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables */
}
